.TH "SPACEBREW\-MIDI" "" "February 2014" "" ""
.SH "NAME"
\fBspacebrew-midi\fR
.P
Route MIDI events via Spacebrew
.SH CLI Utility Usage
.P
The CLI utility is a quick and easy way to connect MIDI devices to the public Spacebrew admin interface\.
.P
Input ports start listening for two Note On events in the background to use as lower and upper boundaries for the range\. The UI doesn\'t currently indicate this is occuring—sorry, bad UX! I\'ll get that fixed in the next version\.
.P
Output ports are currently connected for the entire C\-0 through G\-9 range\.
.P
WARNING: Simultaneous connections of the same type (input or output) segfaults on some platforms\. Looking into the root cause\.\.\.
.P
.RS 2
.EX
$ npm i \-g spacebrew\-midi
$ spacebrew\-midi

Spacebrew MIDI \- Select a device to connect to Spacebrew                    
  \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-  
   INPUT on QUNEO:0                                                         
   INPUT on MPK mini:0                                                      
  OUTPUT on QUNEO:0 \- Connected!                                            
  OUTPUT on MPK mini:0
.EE
.RE
.SH Module Usage Example
.P
.RS 2
.EX
var sbmidi = require("spacebrew\-midi");

// Connect to Spacebrew, passing an onOpen handler
sbmidi\.connect(function () {

  // Determine the last available port, usually the most recently connected device
  var portNumber = sbmidi\.getInPortCount() \- 1;

  // One octave to either side of Middle C
  sbmidi\.addInputRange(portNumber, 48, 72);

  // Similar for output!
  sbmidi\.addOuputRange(portNumber, 48, 72);

  // Alternatively, just pass a port number and bounds will be "learned"
  // based on the next two Note On events received
  sbmidi\.addInputRange(portNumber);

});
.EE
.RE
.P
And over in the Admin interface you\'ll see:
.P
Screenshot of Spacebrew Admin running example code \fIhttps://github\.com/randallagordon/spacebrew\-midi/raw/master/img/readme\-example\.png\fR
.P
By default this will create a connection to the public Spacebrew
Admin \fIhttp://spacebrew\.github\.com/spacebrew/admin/admin\.html?server=sandbox\.spacebrew\.cc\fR
interface\.
.P
To connect to another server: \fBsbmidi\.connect({ server: "http://localhost/" })\fR
.P
To use a different name and description: \fBsbmidi\.connect({ name: "Bob", description: "Bob\'s MIDI Controller" })\fR
.SH CHANGELOG
.SS v0\.2\.0
.RS 0
.IP \(bu 2
Added CLI utility
.IP \(bu 2
Added support for connecting multiple ports simultaneously (still has issues)
.IP \(bu 2
Added input range addition via "learning" from MIDI Note On events

.RE
.SS v0\.1\.1
.RS 0
.IP \(bu 2
Added MIDI output support

.RE
.SH TODO
.RS 0
.IP \(bu 2
Support more MIDI messages than just note on/off
.IP \(bu 2
Use Spacebrew custom messages for sending complex CC messages (knobs, sliders, etc\.)
.IP \(bu 2
Publish MIDI helper library separately
.IP \(bu 2
Add CLI option parsing for non\-interactive routing
.IP \(bu 2
JSON based config files to support building a device map library (think \fBspacebrew\-midi \-\-device QuNeo\fR)
.IP \(bu 2
Web interface to complement CLI for adding/editing routed messages
.IP \(bu 2
Handle closing things down (onClose handler to close MIDI ports, etc\.)
.IP \(bu 2
Refactor so a range can be added on an already open port

.RE
.SH LICENSE
.P
MIT

